---
title: "Introduction"
author: "auth"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, eval=F}
##### ONLY FOR TESTING ####
#fl <- list.files("../R/", full.names=T) 
fl <- c("../R/filter.R" ,"../R/scBMClass.R")
for (f in fl) { source(f) }
###

require(Seurat)
dt1 <- Read10X(data.dir = "../../data/pbmc/filtered_gene_bc_matrices/hg19/")
so <- CreateSeuratObject(counts=dt1, project="test", min.features=200, min.cells=5)
```

# Outline
```{r}
library(R6)

fl <- c("../R/filter.R" ,"../R/scBMClass.R")
for (f in fl) { source(f) }

####
# Create scBM instance w/ Seurat object so
obj <- scBM$new(so)

####
# Apply default filters 
#obj <- filter(obj, ...)

#######
# Identify clusters 
# ... 
# ... 

######
# Extract cluster metrics  -> aggregated metrics for evaluation 
# .. # clusters, cluster size, ...

######
#####
# Assign identity to clusters




```

##########

# Overview
This vignette demonstrates the use of the scBM package.

# Requirements and installation
The package utilizes Seurat. 


